import { StyleSheet } from "react-native";
import colors from "../../styles/colors.styles";

const styles = StyleSheet.create({
  modalSuccess: {
    width: 340,
    height: 139,
    backgroundColor: colors.beige,
    borderTopColor: colors.green,
    borderTopWidth: 40,
    borderLeftColor: colors.grey,
    borderLeftWidth: 2,
    borderBottomColor: colors.grey,
    borderBottomWidth: 2,
    borderRightColor: colors.grey,
    borderRightWidth: 2,
    paddingHorizontal: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderRadius: 15,
    position: "absolute",
    zIndex: 1,
    top: 360,
    left: "8%",
  },
  modalError: {
    width: 340,
    height: 139,
    backgroundColor: colors.beige,
    borderTopColor: colors.wine,
    borderTopWidth: 40,
    borderLeftColor: colors.grey,
    borderLeftWidth: 2,
    borderBottomColor: colors.grey,
    borderBottomWidth: 2,
    borderRightColor: colors.grey,
    borderRightWidth: 2,
    paddingHorizontal: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderRadius: 15,
    position: "absolute",
    zIndex: 1,
    top: 360,
    left: "8%",
  },
  modalText: {
    fontSize: 18,
    textAlign: "center",
  },
  icon: {
    color: colors.grey,
  },
});

export default styles;
