const countries = [
  { label: "Show all", value: "Show all" },
  { label: "Qatar", value: "Qatar" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Senegal", value: "Senegal" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "England", value: "England" },
  { label: "Iran", value: "Iran" },
  { label: "USA", value: "USA" },
  { label: "Wales", value: "Wales" },
  { label: "Argentina", value: "Argentina" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Mexico", value: "Mexico" },
  { label: "Poland", value: "Poland" },
  { label: "France", value: "France" },
  { label: "Australia", value: "Australia" },
  { label: "Denmark", value: "Denmark" },
  { label: "Tunisia", value: "Tunisia" },
  { label: "Spain", value: "Spain" },
  { label: "Costa Rica", value: "Costa Rica" },
  { label: "Germany", value: "Germany" },
  { label: "Japan", value: "Japan" },
  { label: "Belgium", value: "Belgium" },
  { label: "Canada", value: "Canada" },
  { label: "Morocco", value: "Morocco" },
  { label: "Croatia", value: "Croatia" },
  { label: "Brazil", value: "Brazil" },
  { label: "Serbia", value: "Serbia" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Cameroon", value: "Cameroon" },
  { label: "Portugal", value: "Portugal" },
  { label: "Ghana", value: "Ghana" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "South Korea", value: "South Korea" },
];

export default countries;
