const matches = [
  { label: "Qatar vs Ecuador Nov 20", value: "Match1" },
  { label: "England vs Iran Nov 21", value: "Match2" },
  { label: "USA vs Wales Nov 21", value: "Match3" },
  { label: "Senegal vs Netherlands Nov 21", value: "Match4" },
  { label: "Argentina vs Saudi Arabia Nov 22", value: "Match5" },
  { label: "Mexico vs Poland Nov 22", value: "Match6" },
  { label: "Denmark vs Tunisia Nov 22", value: "Match7" },
  { label: "France vs Australia Nov 22", value: "Match8" },
  { label: "Morocco vs Croatia Nov 23", value: "Match9" },
  { label: "Spain vs Costa Rica Nov 23", value: "Match10" },
  { label: "Germany vs Japan Nov 23", value: "Match11" },
  { label: "Belgium vs Canada Nov 23", value: "Match12" },
  { label: "Switzerland vs Cameroon Nov 24", value: "Match13" },
  { label: "Portugal vs Ghana Nov 24", value: "Match14" },
  { label: "Uruguay vs South Korea Nov 24", value: "Match15" },
  { label: "Brazil vs Serbia Nov 24", value: "Match16" },
  { label: "Wales vs Iran Nov 25", value: "Match17" },
  { label: "Netherlands vs Ecuador Nov 25", value: "Match18" },
  { label: "Qatar vs Senegal Nov 25", value: "Match19" },
  { label: "England vs USA Nov 25", value: "Match20" },
  { label: "Tunisia vs Australia Nov 26", value: "Match21" },
  { label: "France vs Denmark Nov 26", value: "Match22" },
  { label: "Poland vs Saudi Arabia Nov 26", value: "Match23" },
  { label: "Argentina vs Mexico Nov 26", value: "Match24" },
  { label: "Japan vs Costa Rica Nov 27", value: "Match25" },
  { label: "Croatia vs Canada Nov 27", value: "Match26" },
  { label: "Belgium vs Morocco Nov 27", value: "Match27" },
  { label: "Cameroon vs Serbia Nov 28", value: "Match28" },
  { label: "Brazil vs Switzerland Nov 28", value: "Match29" },
  { label: "South Korea vs Ghana Nov 28", value: "Match30" },
  { label: "Portugal vs Uruguay Nov 28", value: "Match31" },
  { label: "Ecuador vs Senegal Nov 29", value: "Match32" },
  { label: "Iran vs USA Nov 29", value: "Match33" },
  { label: "Netherlands vs Qatar Nov 29", value: "Match34" },
  { label: "Wales vs England Nov 29", value: "Match35" },
  { label: "Tunisia vs France Nov 30", value: "Match36" },
  { label: "Poland vs Argentina Nov 30", value: "Match37" },
  { label: "Australia vs Denmark Nov 30", value: "Match38" },
  { label: "Saudi Arabia vs Mexico Nov 30", value: "Match39" },
  { label: "Croatia vs Belgium Dic 1", value: "Match40" },
  { label: "Japan vs Spain Dic 1", value: "Match41" },
  { label: "Canada vs Morocco Dic 1", value: "Match42" },
  { label: "Costa Rica vs Germany Dic 1", value: "Match43" },
  { label: "South Korea vs Portugal Dic 2", value: "Match44" },
  { label: "Serbia vs Switzerland Dic 2", value: "Match45" },
  { label: "Ghana vs Uruguay Dic 2", value: "Match46" },
  { label: "Cameroon vs Brazil Dic 2", value: "Match47" },
];

export default matches;
